apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pve-exporter
spec:
  ports:
    - name: http
      port: 9221
      targetPort: 9221
  selector:
    app: {{ .Release.Name }}-pve-exporter
