---
# Source: common/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: common
  namespace: common
  labels:
    app.kubernetes.io/name: common
    helm.sh/chart: common-0.0.1
    app.kubernetes.io/instance: common
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: http
      port: 80
      protocol: UDP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: common
    app.kubernetes.io/instance: common
...
---
# Source: common/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: common
  labels:
    app.kubernetes.io/name: common
    helm.sh/chart: common-0.0.1
    app.kubernetes.io/instance: common
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: common
      app.kubernetes.io/instance: common
  template:
    metadata:
      labels:
        app.kubernetes.io/name: common
        app.kubernetes.io/instance: common
      annotations:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: common
          image: "traefik/whoami:v1.10@sha256:0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: UDP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: exporter
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: exporter
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /health
              port: exporter
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: ENVVAR
              value: TEST
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 1m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            seccompProfile:
              type: RuntimeDefault
...
---
# Source: common/templates/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: common
  namespace: common
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: common
      app.kubernetes.io/instance: common
  endpoints:
    - port: https
...
