---
# Source: frigate-exporter/templates/service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: common-frigate-exporter
  namespace: common-frigate-exporter
  labels:
    app.kubernetes.io/name: frigate-exporter
    helm.sh/chart: frigate-exporter-0.0.12
    app.kubernetes.io/instance: common
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
    - name: exporter
      port: 9100
      protocol: TCP
      targetPort: exporter
  selector:
    app.kubernetes.io/name: frigate-exporter
    app.kubernetes.io/instance: common
...

---
# Source: frigate-exporter/templates/service-monitor.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: common-frigate-exporter
  namespace: common-frigate-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate-exporter
      app.kubernetes.io/instance: common
  endpoints:
    - port: exporter
...
---
# Source: frigate-exporter/templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-frigate-exporter
  namespace: common-frigate-exporter
  labels:
    app.kubernetes.io/name: frigate-exporter
    helm.sh/chart: frigate-exporter-0.0.12
    app.kubernetes.io/instance: common
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: frigate-exporter
      app.kubernetes.io/instance: common
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frigate-exporter
        app.kubernetes.io/instance: common
      annotations:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: frigate-exporter
          image: "rhysbailey/prometheus-frigate-exporter:0.1.1@sha256:6df30ca30c5a69df4f3b21c06a93043a52baf523f808de56f4a40982393b8aff"
          imagePullPolicy: IfNotPresent
          ports:
            - name: exporter
              containerPort: 9100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: exporter
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: exporter
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /metrics
              port: exporter
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: "FRIGATE_STATS_URL"
              value: "http://frigate.{{ include "common.namespace" . }}.svc.cluster.local:5000/api/stats"
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 1m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
...
