fullnameOverride: ""
nameOverride: ""

strategyType: Recreate

frigateApiStatsEndpoint: "http://frigate.frigate.svc.cluster.local:5000/api/stats"
image:
  pullPolicy: IfNotPresent
  repository: rhysbailey/prometheus-frigate-exporter
  tag: latest
imagePullSecrets: []
probes:
  liveness:
    enabled: true
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    failureThreshold: 3
    initialDelaySeconds: 30
    successThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 5
  readiness:
    enabled: true
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    failureThreshold: 3
    initialDelaySeconds: 30
    successThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 5
  startup:
    enabled: true
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    failureThreshold: 3
    initialDelaySeconds: 30
    successThreshold: 1
    periodSeconds: 10
    timeoutSeconds: 5
service:
  annotations: {}
  labels: {}
  port: 9100

# resources: {}
