---
frigateApiStatsEndpoint: http://frigate.frigate.svc.cluster.local:5000/api/stats
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: rhysbailey/prometheus-frigate-exporter
  tag: 0.1.1@sha256:0
imagePullSecrets: []
nameOverride: ''
probes:
  liveness:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readiness:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  startup:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 1m
    memory: 32Mi
# securityContext:
#   allowPrivilegeEscalation: false
#   runAsNonRoot: true
#   runAsUser: 1000
#   seccompProfile:
#     type: RuntimeDefault
#   capabilities:
#     drop: ["ALL"]
#   readOnlyRootFilesystem: true
podSecurityContext:
  allowPrivilegeEscalation: false
  # runAsNonRoot: true
#   runAsUser: 1000
#   seccompProfile:
#     type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
#   readOnlyRootFilesystem: true
service:
  annotations: {}
  labels: {}
  port: 9100
serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  endpoints:
    port: exporter
strategyType: Recreate
