{{- $newEnv := include "frigateExporter.env" . | fromYaml -}}
{{- $_ := set .Values "newEnv" $newEnv -}}
{{- $container := .Values.deployments.main.podSpec.containers.main -}}
{{- $mergedenv := concat $container.env .Values.newEnv.env }}
{{- $_ := set $container "env" $mergedenv -}}

{{- include "common.loader" . -}}
