apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - name: exporter
      port: 9100
      protocol: TCP
      targetPort: exporter
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}
