{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "frigateExporter.fullname" . }}
  namespace: {{ include "frigateExporter.namespace" . }}
  labels:
    release: {{ .Values.serviceMonitor.labels.release }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "frigateExporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.serviceMonitor.endpoints.port }}
...
{{- end -}}
