---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "frigateExporter.fullname" . }}
  namespace: {{ include "frigateExporter.namespace" . }}
  labels:
{{ include "frigateExporter.labels" . | indent 4 }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
    - name: exporter
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: exporter
  selector:
    app.kubernetes.io/name: {{ include "frigateExporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
...
