{{- if gt (len .Values.services) 0 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  namespace: {{ include "common.namespace" . }}
  labels:
{{ include "common.labels" . | indent 4 }}
{{- if .Values.services.labels }}
{{ toYaml .Values.services.labels | indent 4 }}
{{- end }}
{{- with .Values.services.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  ports:
  {{- range $serviceName, $serviceValues := .Values.services.ports }}
    - name: {{ $serviceName }}
      port: {{ $serviceValues.port }}
      protocol: {{ include "common.protocol" $serviceValues.protocol }}
      targetPort: {{ $serviceName }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
...
{{- end -}}
