prometheus:
  server:

    ## Path to a configuration file on prometheus server container FS
    configPath: /etc/config/prometheus.yml

    persistentVolume:
      ## If true, Prometheus server will create/use a Persistent Volume Claim
      ## If false, use emptyDir
      ##
      enabled: false
      volumeName: ""
      storageClass: "-"
      size: 10Gi
      nfs:
        enabled: false
        server: 10.0.0.1
        path: /path

    service:
      ## If false, no Service will be created for the Prometheus server
      ##
      enabled: true

    ingress:
      ## If true, Prometheus server Ingress will be created
      ##
      enabled: false

    ingressroute:
      ## If true, Prometheus server IngressRoute will be created
      ##
      enabled: true
      path: /prometheus/

    ## Prometheus data retention period (default if not specified is 15 days)
    ##
    retention: "15w"

  networkPolicy:
    ## Enable creation of NetworkPolicy resources.
    ##
    enabled: true

  # Configuration of subcharts defined in Chart.yaml

  ## alertmanager sub-chart configurable values
  ## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/alertmanager
  ##
  alertmanager:
    ## If false, alertmanager will not be installed
    ##
    enabled: false

  ## kube-state-metrics sub-chart configurable values
  ## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics
  ##
  kube-state-metrics:
    ## If false, kube-state-metrics sub-chart will not be installed
    ##
    enabled: true

  ## promtheus-node-exporter sub-chart configurable values
  ## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
  ##
  prometheus-node-exporter:
    ## If false, node-exporter will not be installed
    ##
    enabled: true

    rbac:
      pspEnabled: false

    containerSecurityContext:
      allowPrivilegeEscalation: false

  ## pprometheus-pushgateway sub-chart configurable values
  ## Please see https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-pushgateway
  ##
  prometheus-pushgateway:
    ## If false, pushgateway will not be installed
    ##
    enabled: false

# -- Provide a name in place of `prometheus-pve-exporter`

pveExporter:

  image:
    # -- image repository
    repository: prompve/prometheus-pve-exporter
    # -- Overrides the image tag
    tag: "2.3.0"

  # -- Number of replicas
  replicaCount: 1

  # -- The number of old ReplicaSets to retain
  revisionHistoryLimit: 10

  serviceAccount:
    # -- Specifies whether a service account should be created
    create: true

  # -- container-level security context
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 65534

  # service:
  #   # -- Kubernetes service type
  #   type: ClusterIP
  #   # -- Kubernetes port where service is exposed
  #   port: 80

  # -- Resource limits and requests for the controller pods.
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  env:
    pveUser: "prometheus@pve"
    # if you provide an existing secret, no additional secret will be created. Depending on the setting in pveAuthType the secret needs to have password OR tokenName and tokenValue fields.
    pveExistingSecretName: "prometheus-pve-exporter"
    # Optional: set to false to skip SSL/TLS verification
    pveVerifySsl: false
