apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.3
    path: /export/k3s_prometheus
