{{- if .Values.prometheus.server.persistentVolume.nfs.enabled -}}
{{- if ne "" .Values.prometheus.server.persistentVolume.volumeName  -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.prometheus.server.persistentVolume.volumeName }}
  labels:
    app.kubernetes.io/name: {{ .Values.prometheus.server.persistentVolume.volumeName }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: {{ .Values.prometheus.server.persistentVolume.nfs.server }}
    path: {{ .Values.prometheus.server.persistentVolume.nfs.path }}
{{- end -}}
{{- end -}}
