{{- if index .Values "kube-prometheus-stack" "prometheus" "ingressroute" "enabled" -}}
{{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $serviceName }}
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: PathPrefix(`{{ index .Values "kube-prometheus-stack" "prometheus" "ingressroute" "path" }}`)
    services:
    - name: {{ $serviceName }}
      port: 9090
{{- end -}}
