---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.server.persistentVolume.existingClaim }}
  labels:
    app.kubernetes.io/name: {{ .Values.server.persistentVolume.existingClaim }}
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.2.3
    path: /export/k3s_nextcloud
