---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.server.persistentVolume.existingClaim }}
  labels:
    app.kubernetes.io/name: {{ .Values.server.persistentVolume.existingClaim }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.server.persistentVolume.existingClaim }}
