{{- if .Values.prometheus.server.ingressroute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: PathPrefix(`{{ .Values.prometheus.server.ingressroute.path }}`)
    services:
    - name: {{ template "prometheus.name" . }}-{{ .Values.prometheus.server.name }}
      port: 80
{{- end -}}
