---
replicaCount: 1
revisionHistoryLimit: 3
fullnameOverride: ''
containers:
  - name: main-container
args: []
env: {}
image:
  pullPolicy: Always
  repository: traefik/whoami
  tag: v1.10@sha256:1699d99cb4b9acc17f74ca670b3d8d0b7ba27c948b3445f0593b58ebece92f04
imagePullSecrets: []
nameOverride: ''
namespaceOverride: ''
probes:
  enabled: true
  liveness:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /health
      port: main
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readiness:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /health
      port: main
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  startup:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /health
      port: main
      scheme: HTTP
    initialDelaySeconds: 60
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 1m
    memory: 32Mi
podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 65534
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
services:
  main:
    enabled: true
    type: ClusterIP
    annotations: {}
    labels: {}
    ports:
      main:
        protocol: TCP
        port: 80
ingress:
  main:
    enabled: true
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
          - path: /testpath
            pathType: Prefix
      - host: another-chart-example.local
        paths:
          - path: /
            pathType: Prefix
          - path: /testpath
            pathType: Prefix

serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  endpoints:
    - port: main
      # optional scrape settings
      # path: /metrics
      # scheme: http
      # interval: 30s
      # scrapeTimeout: 10s
      metricRelabelings: []
        # - action: replace
        #   sourceLabels: ["__name__"]
        #   regex: "scale_truenas_system_(.*)"
        #   replacement: "truenas_$1"
        #   targetLabel: "__name__"
strategyType: Recreate
