---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}
    tier: frontend
spec:
  ports:
    - name: {{ .Release.Name }}-app
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    tier: frontend
