---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}
    tier: backend
spec:
  ports:
    - name: {{ .Release.Name }}-db
      port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
    tier: backend
