---
# Source: graphite-exporter/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: ma-release-graphite-exporter-graphite
  namespace: ma-release-graphite-exporter
  labels:
    app.kubernetes.io/name: graphite-exporter
    helm.sh/chart: graphite-exporter-0.0.1
    app.kubernetes.io/instance: ma-release
    app.kubernetes.io/managed-by: Helm
spec:
  type: LoadBalancer
  ports:
    - name: graphite-tcp
      port: 9109
      protocol: TCP
      targetPort: graphite-tcp
    - name: graphite-udp
      port: 9109
      protocol: UDP
      targetPort: graphite-udp
  selector:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: ma-release
...
---
# Source: graphite-exporter/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: ma-release-graphite-exporter-main
  namespace: ma-release-graphite-exporter
  labels:
    app.kubernetes.io/name: graphite-exporter
    helm.sh/chart: graphite-exporter-0.0.1
    app.kubernetes.io/instance: ma-release
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: main
      port: 9108
      protocol: TCP
      targetPort: main
  selector:
    app.kubernetes.io/name: graphite-exporter
    app.kubernetes.io/instance: ma-release
...
---
# Source: graphite-exporter/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ma-release-graphite-exporter
  namespace: ma-release-graphite-exporter
  labels:
    app.kubernetes.io/name: graphite-exporter
    helm.sh/chart: graphite-exporter-0.0.1
    app.kubernetes.io/instance: ma-release
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: graphite-exporter
      app.kubernetes.io/instance: ma-release
  template:
    metadata:
      labels:
        app.kubernetes.io/name: graphite-exporter
        app.kubernetes.io/instance: ma-release
      annotations:
    spec:
      automountServiceAccountToken: false
      containers:
        - name: graphite-exporter
          image: "prom/graphite-exporter:v0.16.0@sha256:e54bca6645ea8a9e8c52312a8540de98ad08819d38476c021d77a0eae75bc797"
          imagePullPolicy: IfNotPresent
          ports:
            - name: graphite-tcp
              containerPort: 9109
              protocol: TCP
            - name: graphite-udp
              containerPort: 9109
              protocol: UDP
            - name: main
              containerPort: 9108
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: main
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: main
              scheme: HTTP
            initialDelaySeconds: 30
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /metrics
              port: main
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 5
          args:
            - --graphite.listen-address=:9109
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            seccompProfile:
              type: RuntimeDefault
...
---
# Source: graphite-exporter/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ma-release-graphite-exporter
  namespace: ma-release-graphite-exporter
  labels:
    app.kubernetes.io/name: graphite-exporter
    helm.sh/chart: graphite-exporter-0.0.1
    app.kubernetes.io/instance: ma-release
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: "traefik"
  rules:
    - host: graphite-exporter.trowa-family.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ma-release-graphite-exporter
                port:
                  name: graphite-udp
...
---
# Source: graphite-exporter/templates/common.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ma-release-graphite-exporter
  namespace: ma-release-graphite-exporter
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: graphite-exporter
      app.kubernetes.io/instance: ma-release
  endpoints:
    - port: main
...
