---
image:
  pullPolicy: IfNotPresent
  repository: prom/graphite-exporter
  tag: v0.16.0@sha256:e54bca6645ea8a9e8c52312a8540de98ad08819d38476c021d77a0eae75bc797
probes:
  liveness:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  readiness:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
  startup:
    enabled: true
    failureThreshold: 3
    httpGet:
      path: /metrics
      port: exporter
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5
podSecurityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true
services:
  annotations: {}
  labels: {}
  ports:
    - name: exporter
      port: 9108
      protocol: TCP
    - name: graphite-udp
      port: 9109
      protocol: UDP
    - name: graphite-tcp
      port: 9109
      protocol: TCP
strategyType: Recreate
