---
image:
  pullPolicy: IfNotPresent
  repository: prom/graphite-exporter
  tag: v0.16.0@sha256:e54bca6645ea8a9e8c52312a8540de98ad08819d38476c021d77a0eae75bc797
probes:
  liveness:
    httpGet:
      path: /metrics
  readiness:
    httpGet:
      path: /metrics
  startup:
    httpGet:
      path: /metrics
args:
  - "--graphite.listen-address=:9109"
services:
  main:
    enabled: true
    annotations: {}
    labels: {}
    ports:
      protocol: TCP
      port: 9108
  graphite-udp:
    enabled: true
    annotations: {}
    labels: {}
    ports:
      protocol: UDP
      port: 9109
  graphite-tcp:
    enabled: true
    annotations: {}
    labels: {}
    ports:
      protocol: TCP
      port: 9109
serviceMonitor:
  endpoints:
    port: main
