fullnameOverride: ""
nameOverride: ""

strategyType: Recreate

frigateApiStatsEndpoint: "http://frigate.frigate.svc.cluster.local:5000/api/stats"
image:
  pullPolicy: IfNotPresent
  repository: rhysbailey/prometheus-frigate-exporter
  # tag: 0.1.1
imagePullSecrets: []
probes:
  liveness:
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 30
    timeoutSeconds: 5
  readiness:
    enabled: false
    failureThreshold: 3
    initialDelaySeconds: 30
    timeoutSeconds: 5
  startup:
    enabled: false
    failureThreshold: 3
    periodSeconds: 10
service:
  annotations: {}
  labels: {}
  port: 9100

# resources: {}
