{{- $fullname := include "common.helpers.fullname" . -}}

{{- if not .Values.ghostfolio.auth.existingSecret }}
{{- $authName := printf "%s-secrets" $fullname -}}
{{- $accessSalt := randAlphaNum 32 -}}
{{- $jwtSecret := randAlphaNum 32 -}}
{{- with (lookup "v1" "Secret" .Release.Namespace $authName) }}
  {{- $accessSalt = index .data "ACCESS_TOKEN_SALT" | b64dec -}}
  {{- $jwtSecret = index .data "JWT_SECRET_KEY" | b64dec -}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $authName }}
  namespace: {{ include "common.helpers.namespace" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
  labels:
    {{- include "common.helpers.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCESS_TOKEN_SALT: {{ $accessSalt | quote }}
  JWT_SECRET_KEY: {{ $jwtSecret | quote }}
{{- end }}

{{- if and .Values.statefulsets.redis.enabled (not .Values.ghostfolio.redis.auth.existingSecret) }}
{{- $redisName := printf "%s-redis" $fullname -}}
{{- $redisPass := randAlphaNum 32 -}}
{{- with (lookup "v1" "Secret" .Release.Namespace $redisName) }}
  {{- $redisPass = index .data "REDIS_PASSWORD" | b64dec -}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $redisName }}
  namespace: {{ include "common.helpers.namespace" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
  labels:
    {{- include "common.helpers.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ $redisPass | quote }}
{{- end }}

{{- if and .Values.cnpgClusters.postgresql.enabled (not .Values.ghostfolio.database.bootstrap.existingSecret) }}
{{- $dbName := printf "%s-db-bootstrap" $fullname -}}
{{- $dbUser := .Values.ghostfolio.database.bootstrap.username | default "ghostfolio" -}}
{{- $dbPass := randAlphaNum 32 -}}
{{- with (lookup "v1" "Secret" .Release.Namespace $dbName) }}
  {{- $dbPass = index .data "password" | b64dec -}}
  {{- $dbUser = index .data "username" | b64dec -}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dbName }}
  namespace: {{ include "common.helpers.namespace" . }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/resource-policy: keep
  labels:
    {{- include "common.helpers.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ $dbUser | quote }}
  password: {{ $dbPass | quote }}
{{- end }}
