name: CI

on:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  quality:
    uses: trowaflo/github-actions/.github/workflows/quality.yml@e943dc3a93aff5f9b2bd542b84caa8c62cb4e55a # PR#35
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      actions: read
    with:
      harden_runner_egress_policy: audit
      enable_gitleaks: true
      enable_checkov: true
      enable_actionlint: true
      enable_trivy: true
      enable_dependency_review: true
      enable_yamllint: true
      enable_json_lint: true
