name: Helm Release

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "charts/**"

permissions: read-all

jobs:
  release:
    uses: trowaflo/github-actions/.github/workflows/release-helm.yml@16b746a93e387b41b394d2f0c6000d1f9e5d5a49 # v1.1.0
    permissions:
      contents: write
      pages: write
    with:
      enable_release: true
      release_charts_dirs: "charts/library charts/apps"
