name: Preview Helm Docs

on:
  pull_request:
    branches:
      - main

jobs:
  preview-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install helm-docs
        run: |
          OS=$(uname -s)
          ARCH=$(uname -m)

          case "$ARCH" in
            x86_64)
              ASSET_ARCH="x86_64"
              ;;
            aarch64)
              ASSET_ARCH="arm64"
              ;;
            *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
          esac

          case "$OS" in
            Linux)
              ASSET_OS="Linux"
              ;;
            Darwin)
              ASSET_OS="Darwin"
              ;;
            *)
              echo "Unsupported OS: $OS"
              exit 1
              ;;
          esac

          VERSION=$(curl -s https://api.github.com/repos/norwoodj/helm-docs/releases/latest | jq -r '.tag_name')
          echo "Latest version: $VERSION"
          URL="https://github.com/norwoodj/helm-docs/releases/download/${VERSION}/helm-docs_${VERSION#v}_${ASSET_OS}_${ASSET_ARCH}.tar.gz"

          echo "Downloading from: $URL"
          curl -sSL "$URL" \
            -o helm-docs.tar.gz

          tar -xzf helm-docs.tar.gz -C /usr/local/bin
          rm helm-docs.tar.gz

      - name: Generate documentation
        run: helm-docs
