name: Helm PR Cleanup

on:
  pull_request:
    types: [closed]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    uses: trowaflo/github-actions/.github/workflows/ci-helm-cleanup.yml@320734f56e60664aa9cfeccaf5873e6f8171fc76 # feat/helm-oci-double-publish
    permissions:
      contents: write
      packages: write
      pull-requests: write
    with:
      enable_oci_cleanup: true
    secrets:
      OCI_CLEANUP_TOKEN: ${{ secrets.OCI_CLEANUP_TOKEN }}
