name: Helm PR Cleanup

on:
  pull_request:
    types: [closed]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cleanup:
    uses: trowaflo/github-actions/.github/workflows/helm-pr-cleanup.yml@9d58d4647688c45c876ab4c1072e0d1573b0939c # v4.1.0
    permissions:
      contents: write
      pull-requests: write
