name: Helm CI

on:
  pull_request:
  # Uncomment to scope to charts only:
  #   paths:
  #     - "charts/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm:
    uses: trowaflo/github-actions/.github/workflows/helm.yml@a7086f13b298337461edc6c9ee1ac2ddce212116 # PR#35
    permissions:
      contents: write
      pull-requests: write
      checks: write
      pages: write
    with:
      harden_runner_allowed_endpoints: >-
        github.com:443
        api.github.com:443
        objects.githubusercontent.com:443
        release-assets.githubusercontent.com:443
        registry.npmjs.org:443
        get.helm.sh:443
        tuf-repo-cdn.sigstore.dev:443
        rekor.sigstore.dev:443
        fulcio.sigstore.dev:443
        pypi.org:443
        files.pythonhosted.org:443
        quay.io:443
        cr.kgateway.dev:443
        aureq.github.io:443
        grafana.github.io:443
        portainer.github.io:443
        prometheus-community.github.io:443
        trowaflo.github.io:443
      enable_lint: true
      enable_unittest: true
      enable_docs_check: true
      enable_bump: true
      enable_pr_charts: true
