name: Helm CI

on:
  pull_request:
  # Uncomment to scope to charts only:
  #   paths:
  #     - "charts/**"
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-ci:
    uses: trowaflo/github-actions/.github/workflows/ci-helm.yml@16b746a93e387b41b394d2f0c6000d1f9e5d5a49 # v1.1.0
    permissions:
      contents: write
      checks: write
      pull-requests: write
    with:
      charts_dir: "charts"
      enable_bump: true
      enable_docs: true
      enable_docs_check: true
      enable_lint: true
      enable_pr_charts: true
      enable_unittest: true
      harden_runner_allowed_endpoints: >-
        registry.npmjs.org:443
        tuf-repo-cdn.sigstore.dev:443
        rekor.sigstore.dev:443
        fulcio.sigstore.dev:443
        pypi.org:443
        files.pythonhosted.org:443
        pkg-containers.githubusercontent.com:443
        cdn01.quay.io:443
        aureq.github.io:443
        grafana.github.io:443
        prometheus-community.github.io:443
        trowaflo.github.io:443
