name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install helm-docs
        run: |
          OS=$(uname -s)
          ARCH=$(uname -m)

          case "$ARCH" in
            x86_64)
              ASSET_ARCH="x86_64"
              ;;
            aarch64)
              ASSET_ARCH="arm64"
              ;;
            *)
              echo "Unsupported architecture: $ARCH"
              exit 1
              ;;
          esac

          case "$OS" in
            Linux)
              ASSET_OS="Linux"
              ;;
            Darwin)
              ASSET_OS="Darwin"
              ;;
            *)
              echo "Unsupported OS: $OS"
              exit 1
              ;;
          esac

          VERSION=$(curl -s https://api.github.com/repos/norwoodj/helm-docs/releases/latest | jq -r '.tag_name')
          echo "Latest version: $VERSION"
          URL="https://github.com/norwoodj/helm-docs/releases/download/${VERSION}/helm-docs_${VERSION#v}_${ASSET_OS}_${ASSET_ARCH}.tar.gz"

          echo "Downloading from: $URL"
          curl -sSL "$URL" \
            -o helm-docs.tar.gz

          tar -xzf helm-docs.tar.gz -C /usr/local/bin
          rm helm-docs.tar.gz

      - name: Find charts
        id: charts
        run: |
          echo "paths=$(find . -type f -name Chart.yaml -exec dirname {} \; | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Generate Helm docs
        run: |
          for chart_dir in ${{ steps.charts.outputs.paths }}; do
            helm-docs --chart-search-root $chart_dir
          done

      - name: Commit Helm docs if changed
        run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: update helm chart documentation"
            git push
          fi

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.7.0
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
